obj-m := vc_mipi_camera.o vc_mipi_core.o

vc_mipi_core-objs := vc_mipi/vc_mipi_core.o vc_mipi/vc_mipi_modules.o
vc_mipi_camera-objs := vc_mipi/vc_mipi_camera.o

ccflags-y += -Werror

ccflags-$(CONFIG_TEGRA_OOT_MODULE) += -DNVIDIA -I $(srctree.nvidia-oot)/include -I$(srctree.nvconftest)

dtb-$(CONFIG_TEGRA_OOT_MODULE) += overlay/tegra234-p3767-camera-p3768-vc_mipi-dual-imx.dtbo
